name: CI
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        ruby-version:
          - "3.2"
          - "3.3.3"
        rails-version:
          - "6.1"
          - "7.0"

    env:
      RAILS_VERSION: "${{ matrix.rails-version }}"
      TEST_MSG_ID: "msg-${{ matrix.rails-version }}-${{ matrix.ruby-version }}"
      FANOUT_FASTLY_KEY: ${{ secrets.FANOUT_FASTLY_KEY }}
      FANOUT_SERVICE_ID: ${{ secrets.FANOUT_SERVICE_ID }}
      FANOUT_SERVICE_URL: ${{ secrets.FANOUT_SERVICE_URL }}
      ANYCABLE_URL: ${{ secrets.ANYCABLE_URL }}
      ANYCABLE_BROADCAST_KEY: ${{ secrets.ANYCABLE_BROADCAST_KEY }}

    name: ${{ format('Tests (Ruby {0}, Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v1

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Print context
        run: echo "$GITHUB_CONTEXT"

      - name: Bundle
        run: bundle install

      - name: Prepare test database
        run: |
          bin/rails db:create db:migrate

      - name: Run tests [fanout]
        env:
          TURBO_TRAIN_TEST_SERVER: fanout
        run: |
          bin/test test/**/*_test.rb

      - name: Run tests [anycable]
        env:
          TURBO_TRAIN_TEST_SERVER: anycable
        run: |
          bin/test test/**/*_test.rb

